import { Nunito } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navBar/NavBar";

const font = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Cafe Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
